name: Open Thread Border Router
run-name: 'Backbone: ${{ inputs.BACKBONE_ROUTER }}, Border: ${{ inputs.BORDER_ROUTING }}, NAT64: ${{ inputs.NAT64 }}, DNS64: ${{ inputs.DNS64 }}'
on:
  workflow_dispatch:
    inputs:
      BACKBONE_ROUTER:
        description: BACKBONE_ROUTER
        required: true
        default: '1'
        type: choice
        options:
          - '0'
          - '1'
      BORDER_ROUTING:
        description: BORDER_ROUTING
        required: true
        default: '1'
        type: choice
        options:
          - '0'
          - '1'
      NAT64:
        description: NAT 64
        required: true
        default: '0'
        type: choice
        options:
          - '0'
          - '1'
      DNS64:
        description: DNS 64
        required: true
        default: '0'
        type: choice
        options:
          - '0'
          - '1'
      DHCPV6_PD:
        description: DHCPV6_PD
        required: true
        default: '0'
        type: choice
        options:
          - '0'
          - '1'
      DHCPV6_PD_REF:
        description: DHCPV6_PD_REF
        required: true
        default: '0'
        type: choice
        options:
          - '0'
          - '1'
      WEB_GUI:
        description: WEB_GUI
        required: true
        default: '1'
        type: choice
        options:
          - '0'
          - '1'
      REST_API:
        description: REST_API
        required: true
        default: '1'
        type: choice
        options:
          - '0'
          - '1'
      INFRA_IF_NAME:
        description: network interface name
        required: true
        default: 'eth0'
        type: string
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      BACKBONE_ROUTER: ${{ inputs.BACKBONE_ROUTER }}
      BORDER_ROUTING: ${{ inputs.BORDER_ROUTING }}
      NAT64: ${{ inputs.NAT64 }}
      DNS64: ${{ inputs.DNS64 }}
      DHCPV6_PD: ${{ inputs.DHCPV6_PD }}
      DHCPV6_PD_REF: ${{ inputs.DHCPV6_PD_REF }}
      WEB_GUI: ${{ inputs.WEB_GUI }}
      REST_API: ${{ inputs.REST_API }}
      INFRA_IF_NAME: ${{ inputs.INFRA_IF_NAME }}
    steps:
      - uses: actions/checkout@v6
        with:
          repository: 'openthread/ot-br-posix'
          fetch-depth: '1'
          path: ot-br-posix
      - run: bash ./script/bootstrap
        working-directory: ot-br-posix
      - run: bash ./script/setup
        working-directory: ot-br-posix
      - name: copy agent artifacts
        run: |
          mkdir -p .debpkg-agent/usr/bin
          cp /usr/sbin/otbr-agent .debpkg-agent/usr/bin/otbr-agent
          mkdir -p .debpkg-agent/etc/dbus-1/system.d/
          cp  /etc/dbus-1/system.d/otbr-agent.conf  .debpkg-agent/etc/dbus-1/system.d/otbr-agent.conf
          mkdir -p .debpkg-agent/usr/lib/systemd/system/
          cp /usr/lib/systemd/system/otbr-agent.service .debpkg-agent/usr/lib/systemd/system/otbr-agent.service
          mkdir -p .debpkg-agent/etc/default/
          cp /etc/default/otbr-agent .debpkg-agent/etc/default/otbr-agent
      - name: copy ctl artifacts
        run: |
          mkdir -p .debpkg-ctl/usr/bin
           cp /usr/sbin/ot-ctl .debpkg-ctl/usr/bin/ot-ctl
      - name: copy web artifacts
        if: ${{ inputs.WEB_GUI || inputs.REST_API }}
        run: |
          mkdir -p .debpkg-web/usr/bin
          cp /usr/sbin/otbr-web .debpkg-web/usr/bin/otbr-web
          mkdir -p .debpkg-web/usr/lib/systemd/system/
          cp /usr/lib/systemd/system/otbr-web.service .debpkg-web/usr/lib/systemd/system/otbr-web.service
          mkdir -p .debpkg-web/usr/share/otbr-web/frontend/
          cp -r /usr/share/otbr-web/frontend/ .debpkg-web/usr/share/otbr-web/frontend/
      - uses: jiro4989/build-deb-action@v4
        name: package agent
        with:
          package: OpenThreadBorderRouterAgent
          package_root: .debpkg-agent
          maintainer: nobody
          version: '1'
          arch: 'amd64' # optional
          depends: '' # optional
          pre_depends: 'libc6 (>= 2.2.1)' # optional
          desc: 'Open Thread Border Router' # optional
          homepage: 'https://github.com/openthread/ot-br-posix/'
          section: 'unknown'   # optional
          priority: 'required' # optional
      - uses: jiro4989/build-deb-action@v4
        name: package cli
        with:
          package: OpenThreadBorderRouterCLI
          package_root: .debpkg-cli
          maintainer: nobody
          version: '1'
          arch: 'amd64' # optional
          depends: '' # optional
          pre_depends: 'libc6 (>= 2.2.1)' # optional
          desc: 'Open Thread Border Router' # optional
          homepage: 'https://github.com/openthread/ot-br-posix/'
          section: 'unknown'   # optional
          priority: 'required' # optional
      - uses: jiro4989/build-deb-action@v4
        name: package web
        if: ${{ inputs.WEB_GUI || inputs.REST_API }}
        with:
          package: OpenThreadBorderRouterWeb
          package_root: .debpkg-web
          maintainer: nobody
          version: '1'
          arch: 'amd64' # optional
          depends: '' # optional
          pre_depends: 'libc6 (>= 2.2.1)' # optional
          desc: 'Open Thread Border Router' # optional
          homepage: 'https://github.com/openthread/ot-br-posix/'
          section: 'unknown'   # optional
          priority: 'required' # optional
      - name: 'Upload Artifact'
        uses: actions/upload-artifact@v7
        with:
          name: Debian package amd64
          path: '*.deb'